kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: device-controller
subjects:
  - kind: ServiceAccount
    name: device-controller
    namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: device-controller